packages:
  - packages/*
  - packages/domains/*
  - workers/*
  - services/*
  - tests/*
  - scripts/migration

catalogs:
  default:
    '@cloudflare/workers-types': ^4.20260213.0
    '@neondatabase/serverless': ^1.0.2
    '@ts-rest/core': ^3.52.1
    '@types/node': ^25.2.3
    bullmq: ^5.69.1
    drizzle-kit: ^0.31.9
    drizzle-orm: ^0.45.1
    hono: ^4.11.10
    ioredis: ^5.9.3
    pino: ^10.3.1
    tailwindcss: ^4.1.18
    typescript: ^5.9.3
    vitest: ^4.0.18
    zod: ^4.3.6
