packages:
  - packages/*
  - packages/domains/*
  - workers/*
  - services/*
  - tests/*
  - scripts/migration

catalogs:
  default:
    '@biomejs/biome': ^2.4.3
    '@cloudflare/workers-types': ^4.20260219.0
    '@neondatabase/serverless': ^1.0.2
    '@ts-rest/core': ^3.52.1
    '@ts-rest/serverless': ^3.52.1
    '@types/node': ^25.3.0
    bullmq: ^5.69.3
    drizzle-kit: ^0.31.9
    drizzle-orm: ^0.45.1
    hono: ^4.12.0
    ioredis: ^5.9.3
    pino: ^10.3.1
    tailwindcss: ^4.2.0
    typescript: ^5.9.3
    vitest: ^4.0.18
    zod: ^4.3.6
